### PR TITLE
Yellow slug added

### PR DESCRIPTION
**Pull request by akbajwa**

### CODE REVIEW

**Comment by akbajwa** [comment]
@vikhyatsingh123 please review this one,i tried a lot fixing this.I have made 3 PRs and they got accepted please help me with the 4th one.I would be really grateful.

**Comment by vikhyatsingh123** [comment]
What are you trying to do? 
Are you beginner or just trying to complete 4 pr of Hacktoberfest

**Comment by vikhyatsingh123** [comment]
Don't do that here

**Comment by akbajwa** [comment]
@vikhyatsingh123 i am beginner , trying for hactoberfest

**Comment by vikhyatsingh123** [comment]
So, first read readme section. There is properly written how to contribute

**Pull request closed without merging**
