### PR TITLE
Smooth transition css added on card and pokemon image, and update sli…

### PR DESCRIPTION
**Pull request by Zalasanjay**
**Update Card and avatar image CSS**

*Previous and Next Button icon on slider has not proper css*
Old btn css

*Corrected Button css*
new slider btn css

*Updated Cards with css transition*
KO2Rk006Dm

### CODE REVIEW

**Comment by Zalasanjay** [comment]
In my second commit i have just formatted index.html file and added new slug card. that's why it is showing that much changes.

**Comment by vikhyatsingh123** [comment]
it's 1988 lines deleted. how can i review that

**Comment by Zalasanjay** [comment]
> it's 1988 lines deleted. how can i review that

Actually there is just line indentation change using default file format in VS Code

**Comment by vikhyatsingh123** [comment]
I can't review this code

**Pull request closed without merging**
