### PR TITLE
Update Index.html

### PR DESCRIPTION
**Pull request by Someshb0512**
Added New Slug

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@Someshb0512 check your image extension. Image is not showing on website

**Comment by vikhyatsingh123** [comment]
@Someshb0512 After correcting, again do PR

**Comment by Someshb0512** [comment]
> @Someshb0512 check your image extension. Image is not showing on website
The extension is correct .png please check again it is working correctly on my side
Capture

**Comment by Someshb0512** [comment]
> @Someshb0512 After correcting, again do PR

It is already correct in my original PR. It is working for me. Screen Shot is in the message

**Comment by vikhyatsingh123** [comment]
@Someshb0512 Image is not loading on the webpage. I think there is an error due to image extension .PNG instead of .png . Once change it and then again do pull request.

**Pull request merged**
