### PR TITLE
Modified some formatting and Udated

### PR DESCRIPTION
**Pull request by sourabhm01**
Fixed some card disorder.
Added heroes section and images.
you can check below screenshot.
Screenshot 2023-10-08 113619
Screenshot 2023-10-08 113547
Screenshot 2023-10-08 113723
Screenshot 2023-10-08 113645

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
why did you change so much lines?

**Comment by sourabhm01** [comment]
> why did you change so much lines?

There are some slugs cards not arranged perfectly.. I arranged them and added new section of heroes of slugtera

image

**Comment by vikhyatsingh123** [comment]
it's fine but you have changed 3k lines. how can i review it all

**Comment by vikhyatsingh123** [comment]
you can make another pr in which only change the lines that are needed

**Comment by sourabhm01** [comment]
> it's fine but you have changed 3k lines. how can i review it all

see the result. Not the code

**Comment by sourabhm01** [comment]
> you can make another pr in which only change the lines that are needed

but there are some cards that are not perfectly arranged see you your repo

**Comment by vikhyatsingh123** [comment]
ok, resolve conflicts. I will see it

**Comment by sourabhm01** [comment]
> ok, resolve conflicts. I will see it

what should I do next?

**Comment by vikhyatsingh123** [comment]
take pull from main branch. it will show conflicts. you have to resolve it then do add, commit and push the changes

**Pull request merged**
